// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  picture: defineAsyncComponent(() => import("./Picture/index.vue")),
  product: defineAsyncComponent(() => import("./Product/index.vue")),
  text: defineAsyncComponent(() => import("./Text/index.vue")),
});
