// Code generated by Slice Machine. DO NOT EDIT.

import { defineSliceZoneComponents } from "@prismicio/vue"
import { defineAsyncComponent } from "vue"

export const components = defineSliceZoneComponents({
	picture: defineAsyncComponent(() => import("./Picture/index.vue")),
	product: defineAsyncComponent(() => import("./Product/index.vue")),
	text: defineAsyncComponent(() => import("./Text/index.vue")),
})
